# Generated by Django 5.0.1 on 2024-08-01 16:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_bookings_booking_date'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='address',
            field=models.ForeignKey(db_column='address_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 1, 21, 34, 43, 676331)),
        ),
    ]
