# Generated by Django 5.0.1 on 2024-08-01 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_bookings_address_alter_bookings_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='address',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 1, 21, 50, 6, 315883)),
        ),
    ]
